#! /bin/bash
#
# gen_bash_script - generate bash script via a templete
#
# usage: gen_bash_script NAME

PROGRAM=$(basename "$0")

usage ()
{
	echo "usage: $PROGRAM NAME"
	return 0
}

if echo $1 | grep -qvE '^[a-zA-Z_][a-zA-Z0-9_]*$'; then
	echo "$PROGRAM: Unavailable name!"
	usage
	exit 1
fi

if [[ -e $1.sh ]]; then
	echo "$PROGRAM: File exists!"
	usage
	exit 2
fi

# Generate script
cat << EOF > $1.sh
#! /bin/bash
#
# Automatically generated by gen_bash_script.sh
#
# TODO

$1 ()
{
	# Verbose & TAG
	local VBS=\${VBS:-true}
	local TAG=\${TAG:-\${FUNCNAME[0]}}

	# TODO

	return \$?
}

# Script can be used as a program or a function
if echo \$0 | grep -qvE '^[-]?bash'; then

	# Global VARs
	PRO=\$(basename "\$0")
	VBS=true
	TAG=\$PRO

	# Show usage
	usage ()
	{
		cat << USAGE_END
Usage: \$PRO 
USAGE_END

		return 0
	}

	# Main
	$1 "\$@"
fi
EOF

echo "$PROGRAM: Bash script $1.sh generated."
