#! /bin/bash

loopdownloader()
{
	local tag="${FUNCNAME[0]}"
	local debug=false

	local head="$1"
	[[ -z "$1" ]] && return 1

	local last=
	local page=
	local line=
	local jpgfile=

	while [[ $head != $last ]]
	do
		wget -nv -c "$head"
		page=${head##*/}
		line=$(cat "$page" | sed 's/iframe/\n/g' | sed -n '10p')
		last=$head
		head=$(echo "$line" | sed 's/><a href="//' | sed 's/"><img src=".*//')
		jpgfile=$(echo "$line" | sed 's/.*"><img src="//' | sed 's/" style=".*//')
		wget -nv -c "$jpgfile"
	done

	return $?
}

loopdownloader "$@"

