#! /bin/bash

if echo $0 | grep -qvE '^[-]?bash'; then
	exit 0
else
	return 0
fi

################################################################################
PS4='+[$SHELL][$BASH_SUBSHELL][$PPID-$$][$LINENO]["${BASH_SOURCE[*]}"][${FUNCNAME[*]}][${BASH_LINENO[*]}]\n   +'
date --date='yesterday' +%y%m%d%H%M%S
${1:+_$1}

sed -i 's#aaaaa#ccccc#' filename

yes | for ((i=0; i<10; ++i)) do
		read -p 'aaaaa' line
		#echo $line
	  done

find . -name *.[chS]

hidden_prompt() {
    unset output
    prompt="$1"
    outvar="$2"
    while read -s -n 1 -p "$prompt" c; do \
        if [ "x$c" = "x" ]; then \
            break
        fi
        prompt='*'
        output="${output}${c}"
    done
    echo
    eval $outvar="$output"
    unset output
}

sed -e 's#/bin#'$HOME'/bin#g' /etc/passwd | grep '/bin'

echo 'aaaa' | md5sum | cut -d' ' -f1

tail -F $TMPLOG

if [ "$V" != 0 ] ; then
    run () {
        echo "## COMMAND: $@"
        $@
    }
else
    run () {
        $@ >>$TMPLOG 2>&1
    }
fi

sed -e 's/John/&, demonstrated/w tmp' -e 's/Alice/&, demonstrated/w tmp2' list

# For a description of the file format, see the Users Guide
# http://cygwin.com/cygwin-ug-net/using.html#mount-table

# This is default anyway:
# none /cygdrive cygdrive binary,posix=0,user 0 0

# /tmp
/cygdrive/r/TEMP /tmp vfat bind 0 0
