#! /bin/bash

exit 0

################################################################################
PS4='+[$SHELL][$BASH_SUBSHELL][$PPID-$$][$LINENO]["${BASH_SOURCE[*]}"][${FUNCNAME[*]}][${BASH_LINENO[*]}]\n   +'
date --date='yesterday' +%y%m%d%H%M%S
${1:+_$1}

yes | for ((i=0; i<10; ++i)) do
		read -p 'aaaaa' line
		#echo $line
	  done

find . -name *.[chS]

hidden_prompt() {
    unset output
    prompt="$1"
    outvar="$2"
    while read -s -n 1 -p "$prompt" c; do \
        if [ "x$c" = "x" ]; then \
            break
        fi
        prompt='*'
        output="${output}${c}"
    done
    echo
    eval $outvar="$output"
    unset output
}

echo 'aaaa' | md5sum | cut -d' ' -f1

tail -F $TMPLOG

# show ASCII
printf "%x\n" "'s"

# gcc word in no-cygwin mode, click to run in Windows
gcc -mno-cygwin -Wall rgb2bmp.c -o rgb2bmp
