#! /bin/bash

## IF NOT DEFINE __LIST_PULL__
[[ -z $__LIST_PULL__ ]] && {
	__LIST_PULL__=true
	
	# clean_html [dir]
	clean_html()
	{
		$(cd "${1:-.}" && find -type f \( -name '*.htm' -o -name '*.html' \) -print0 | xargs -0 rm -f)
	}

	# html_filter rule file|list [prefix]
	html_filter()
	{
		local files=$2
		local prefix=${3:-.}

		[[ $2 = *.list ]] && files=$(cat $2)

		mkdir -p $prefix

		case $1 in
		img.moko_cc)
			grep '<p class="picBox">' $files | cut -d\" -f4 > $prefix/img.list
			;;
		esac
	}

	# list_dump link|list [prefix]
	lxxx_download()
	{
		local GET="wget -c -nv -P ${2:-.}" 
					
		case $1 in
		http://*)
			$GET $1
			;;
		*.list)
			$GET -i $1
			mv $1 $1.done
			;;
		esac
	}
}
