#! /bin/bash

## Get absolute path of a file or a directory.
# usage: get_abspath [file|dir]
get_abspath()
{
	# cd a directory and pwd
	if [[ -z "$1" ]]; then
		echo "$(pwd)"
	elif [[ -d "$1" ]]; then
		echo "$(cd "$1"; pwd)"
	elif [[ -f "$1" ]]; then
		# file just under / has only one '/'
		# $1 contains no '/' 2>/dev/null
		[[ -n "${1%/*}" ]] && echo -n "$(cd ${1%/*} 2>/dev/null; pwd)"
		echo "/${1##*/}"
	fi

	return $?
}
