#! /bin/bash
#
# get_abspath - get absolute path of a file or a directory
#
# Usage:
#           get_adspath PATH
#
#   @PATH: path should be available
#
get_abspath ()
{		
	if [[ -d $1 ]]; then
		echo $(cd "$1"; pwd)
	elif [[ -f $1 ]]; then
		if [[ $1 == /* ]]; then
			echo $(cd "${1%/*}"; pwd)/${1##*/}
		else
			echo $(cd "$(pwd)/${1%/*}"; pwd)/${1##*/}
		fi
	fi
}
